### ISSUE TITLE
loading when autoplay

### ISSUE THREAD

**Issue by farrelanelca** [CaiJingLong/flutter_ijkplayer#134]
**Circle Progress bar  **

Adding circle progress bar when await video source, becaxuse it will distorted when auto play
![image](https://user-images.githubusercontent.com/42790915/64777391-42862e00-d584-11e9-8a3c-498b01854656.png)

![1568284833512](https://user-images.githubusercontent.com/42790915/64777500-7bbe9e00-d584-11e9-9326-b800ad3e48fc.gif)

**Comment by CaiJingLong** [comment]
The reason for this is because the size/angle of the current video is notified to the dart after the video information is obtained.

There are two way:
1. Get the size of the video in advance (server api, local api), wrap your ijkplayer with Container or other Widget.

2. [Customize Texture](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/README-EN.md#use-texture-widget), only display Texture when video playing.

**Comment by farrelanelca** [comment]
okeyy, fixed thank :)
